[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

[licenses]
allow = ["MIT", "Apache-2.0"]

[bans]
wildcards = "deny"
deny = [
    { name = "serde_derive", version = ">=1.0.172" }
]
